### ISSUE TITLE
编译PHYLIPNEW-3.69.650报错

### ISSUE THREAD

**Issue by WWz33** [hewm2008/VCF2Dis#1]
/usr/bin/ld: disc.o:(.bss+0x38): multiple definition of `phylostates'; clique.o:(.bss+0x4a0): first defined here
/usr/bin/ld: phylip.o:(.bss+0x50): multiple definition of `embossouttree'; clique.o:(.bss+0xf8): first defined here
/usr/bin/ld: phylip.o:(.bss+0x68): multiple definition of `embossoutfile'; clique.o:(.bss+0x100): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1078: fclique] Error 1
make[2]: Leaving directory '/home/ww/biosoft/PHYLIPNEW-3.69.650/src'
make[1]: *** [Makefile:981: all] Error 2
make[1]: Leaving directory '/home/ww/biosoft/PHYLIPNEW-3.69.650/src'
make: *** [Makefile:351: all-recursive] Error 1
这个方法可以解决https://www.jianshu.com/p/8205095e50cd

**Comment by hewm2008** [comment]
你好 ，这软件是第三方的，安装麻烦。  实在麻烦，建议直接用下面这两个网址，上传数据  几分钟就出结果 

Choose one of A/B
A. Upload the web [fneighbor(http://emboss.toulouse.inra.fr/cgi-bin/emboss/fneighbor?_pref_hide_optional=1)](http://emboss.toulouse.inra.fr/cgi-bin/emboss/fneighbor?_pref_hide_optional=1) ，the Click the Run fneighbor bottom . then you can get the output file datafile.treefile
B. Upload the p_dis.mat to the website [fastme (http://www.atgc-montpellier.fr/fastme/)](http://www.atgc-montpellier.fr/fastme/), select Data Type to the Distance matrix ,Click the bottom twist execute & email results. you will get the p_dis_mat_fastme-tree.nwk , and Email not mandatory;

**Comment by timizeng** [comment]
Thanks for the wonderful illustration:
I would like to suggest installing this by Conda/mamba, like `mamba install -c bioconda embassy-phylip` which will contain the tools that all need.
cheers!

**Comment by hewm2008** [comment]
1.52版本 更快计算  同时调用新的构树方法  一步到位。

**Comment by peterjc** [comment]
The bioconda package version of `fconsense` was failing but I have updated that now.

To fix the `multiple definition of ...` errors if compiling, add `-fcommon` to `CFLAGS`.
